### ISSUE TITLE
Unexpected end of JSON input error

### ISSUE THREAD

**Issue by Amith92** [pozil/salesforce-node-client#8]
I cloned the react sample app and ran it with my SF credentials and after authentication, I get the below error - 

`Force.com authentication error: {"message":"Unexpected end of JSON input","statusCode":500,"response":""}`

I'm running the app on my localhost and have used https://localtunnel.github.io/www/ which gives me a publically accessible URL. 

When I hit the route - `/auth/login`, it redirects to SF login and in the sfdc.auth.authenticate,
it gets a 302 response and then fails here.

Any help is appreciated, thanks in advance!

**Comment by pozil** [comment]
Hi @Amith92, I just cloned and set up the sample app from scratch and I was able to make it work without any problem.

In order to help I updated the readme of the sample app with a sample `.env` file template. Make sure that you have this in your app's root folder.

Also, why would you need this localtunnel thing?
You can just run the sample app on your local host. Try that first and make sure that it works.

**Comment by Amith92** [comment]
Thanks for the response @pozil! This may have been something to do with how the salesforce app was set up. For now, I have fixed it by handling the 302 inside callService method by sending a post request to URL at response.headers.location. 

You can close this if you think this is not an issue with the package.
